//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class study_students
    {
        public int id { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public bool sex { get; set; }
        public Nullable<int> class_id { get; set; }
    }
}
